# Generated by Django 6.0.1 on 2026-01-20 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=100)),
                ('referencia', models.TextField(blank=True, help_text='Ej: Casa color verde junto a la tienda.')),
                ('estado', models.CharField(choices=[('pendiente', '💳 Pago Pendiente'), ('preparando', '📦 En Preparación'), ('enviado', '🚚 En Camino'), ('entregado', '✅ Entregado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50, unique=True, verbose_name='Cód. Producto')),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Referencia')),
                ('nombre', models.CharField(max_length=255, verbose_name='Descripción/Nombre')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo Contable')),
                ('linea_nombre', models.CharField(max_length=100, verbose_name='Nombre Línea')),
                ('existencia_bodega', models.IntegerField(default=0, verbose_name='Stock Real')),
                ('stock_minimo', models.IntegerField(default=1, verbose_name='Mínimo')),
                ('stock_maximo', models.IntegerField(default=100, verbose_name='Máximo')),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=50, verbose_name='U. Medida')),
                ('precio_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Normal (PVP)')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Descuento')),
                ('costo_promedio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Costo Unitario')),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='% IVA')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/', verbose_name='Imagen del Producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible en Web')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría Web')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario de Productos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'unique_together': {('user', 'producto')},
            },
        ),
    ]
